#!/usr/bin/env bash

eval `osxcross-conf`
type=`basename $0`

if [ "$type" != "${type/o64/}" ] || [ "$type" != "${type/x86_64/}" ]; then
    ARCH1="x86_64"
    ARCH2=$ARCH1
else
    if [ "$type" != "${type/o32/}" ] || [ "$type" != "${type/i386/}" ]; then
        ARCH1="i386"
        ARCH2="i686"
    else
        echo "unknown arch"
        exit 1
    fi
fi

if [ "$type" != "${type/++/}" ]; then
    COMPILER="$OSXCROSS_TARGET_DIR/bin/$ARCH1-apple-$OSXCROSS_TARGET-base-g++"
    OSXCROSS_OPT_ARGS+=" -static-libgcc -static-libstdc++ -arch $ARCH1"
else
    COMPILER="$OSXCROSS_TARGET_DIR/bin/$ARCH1-apple-$OSXCROSS_TARGET-base-gcc"
    OSXCROSS_OPT_ARGS+=" -static-libgcc -arch $ARCH1"
fi

if [ "$OSXCROSS_OSX_VERSION_MIN" != "default" ]; then
    OSX_VERSION_MIN_OPT="-mmacosx-version-min=$OSXCROSS_OSX_VERSION_MIN"
else
    OSX_VERSION_MIN_OPT=""
fi

export COMPILER_PATH="$OSXCROSS_CCTOOLS_PATH:${COMPILER_PATH}"

$COMPILER $OSX_VERSION_MIN_OPT $OSXCROSS_OPT_ARGS ${1+"$@"}

exit $?
