#!/usr/bin/env bash

eval `osxcross-conf`
type=`basename $0`

if [ "$type" != "${type/o64/}" ] || [ "$type" != "${type/x86_64/}" ]; then
    ARCH1="x86_64"
    ARCH2=$ARCH1
else
    if [ "$type" != "${type/o32/}" ] || [ "$type" != "${type/i386/}" ]; then
        ARCH1="i386"
        ARCH2="i686"
    else
        echo "unknown arch"
        exit 1
    fi
fi

if [ "$type" != "${type/++/}" ]; then
    COMPILER="clang++"
else
    COMPILER="clang"
fi

if [ $# -gt 0 ]; then
    for p in "$@"
    do
        if [[ "$p" == -mmacosx-version-min=* ]]; then
            OSXCROSS_OSX_VERSION_MIN="default"
            break
        fi
    done
fi

if [ "$OSXCROSS_OSX_VERSION_MIN" != "default" ]; then
    OSX_VERSION_MIN_OPT="-mmacosx-version-min=$OSXCROSS_OSX_VERSION_MIN"
else
    OSX_VERSION_MIN_OPT=""
fi

export COMPILER_PATH="$OSXCROSS_CCTOOLS_PATH:${COMPILER_PATH}"

STDINC=$OSXCROSS_SDK/usr/include
CPLUSINC1=$OSXCROSS_SDK/usr/lib/gcc/i686-apple-$OSXCROSS_TARGET/4.2.1/include
CPLUSINC2=$OSXCROSS_SDK/usr/include/c++/4.0.0
CPLUSINC3=$OSXCROSS_SDK/usr/include/c++/4.0.0/$ARCH2-apple-darwin9
TARGET=$ARCH1-apple-$OSXCROSS_TARGET

XMMINTRIN=`readlink "$STDINC/xmmintrin.h"`
if [ $? -eq 0 ] && [ ! -f "$XMMINTRIN" ]; then
    echo "oclang error: dead intrinsic link found - please re-run ./build.sh" 1>&2
    exit 1
fi

$COMPILER $OSXCROSS_TARGET_OPTION $TARGET -isysroot $OSXCROSS_SDK \
-isystem $STDINC -isystem $CPLUSINC1 -isystem $CPLUSINC2 -isystem $CPLUSINC3 \
$OSX_VERSION_MIN_OPT -mlinker-version=$OSXCROSS_LINKER_VERSION $OSXCROSS_OPT_ARGS \
${1+"$@"}

exit $?
